/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cart = Array<CartItem>;
export interface CartItem {
  'menuItemUuid' : string,
  'restaurantUuid' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type CuisineType = { 'other' : string } |
  { 'chicken' : null } |
  { 'chinese' : null } |
  { 'healthy' : null } |
  { 'mexican' : null } |
  { 'fastFood' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'american' : null } |
  { 'pizza' : null } |
  { 'burger' : null } |
  { 'barbecue' : null };
export type ExternalBlob = Uint8Array;
export interface FoodCourtProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface LiveOrder {
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'orderId' : string,
  'items' : Array<OrderMenuItem>,
  'totalPrice' : bigint,
  'orderTimestamp' : bigint,
}
export interface MenuItem {
  'name' : string,
  'uuid' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantUuid' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'userId' : Principal,
  'userNotes' : string,
  'uuid' : string,
  'restaurantId' : string,
  'items' : Array<OrderMenuItem>,
  'totalPrice' : bigint,
  'orderTimestamp' : bigint,
}
export interface OrderMenuItem {
  'uuid' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null };
export interface Restaurant {
  'name' : string,
  'uuid' : string,
  'cuisineType' : CuisineType,
  'description' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export interface UpdateCartItemInput {
  'menuItemUuid' : string,
  'quantity' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'addSearchHistory' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearActiveOrders' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'filterMenuByPriceRange' : ActorMethod<[bigint, bigint], Array<MenuItem>>,
  'getAllActiveOrders' : ActorMethod<[], Array<LiveOrder>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FoodCourtProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartItems' : ActorMethod<[], Cart>,
  'getMenuByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getMenuItem' : ActorMethod<[string], MenuItem>,
  'getOrder' : ActorMethod<[string], Order>,
  'getSingleRestaurant' : ActorMethod<[], Restaurant>,
  'getStandardizedRestaurantContactInfo' : ActorMethod<[], string>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [FoodCourtProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderAsDelivered' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<[string, string, string, string], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[FoodCourtProfile], undefined>,
  'searchMenuByName' : ActorMethod<[string], Array<MenuItem>>,
  'updateCartItems' : ActorMethod<[Array<UpdateCartItemInput>, boolean], Cart>,
  'updateMenuItem' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];