/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'uuid' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantUuid' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'menuItemUuid' : IDL.Text,
  'restaurantUuid' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
});
export const OrderMenuItem = IDL.Record({
  'uuid' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const LiveOrder = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'customerPhone' : IDL.Text,
  'orderId' : IDL.Text,
  'items' : IDL.Vec(OrderMenuItem),
  'totalPrice' : IDL.Nat,
  'orderTimestamp' : IDL.Int,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'customerPhone' : IDL.Text,
  'userId' : IDL.Principal,
  'userNotes' : IDL.Text,
  'uuid' : IDL.Text,
  'restaurantId' : IDL.Text,
  'items' : IDL.Vec(OrderMenuItem),
  'totalPrice' : IDL.Nat,
  'orderTimestamp' : IDL.Int,
});
export const FoodCourtProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Cart = IDL.Vec(CartItem);
export const CuisineType = IDL.Variant({
  'other' : IDL.Text,
  'chicken' : IDL.Null,
  'chinese' : IDL.Null,
  'healthy' : IDL.Null,
  'mexican' : IDL.Null,
  'fastFood' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'american' : IDL.Null,
  'pizza' : IDL.Null,
  'burger' : IDL.Null,
  'barbecue' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'name' : IDL.Text,
  'uuid' : IDL.Text,
  'cuisineType' : CuisineType,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const UpdateCartItemInput = IDL.Record({
  'menuItemUuid' : IDL.Text,
  'quantity' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'addSearchHistory' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearActiveOrders' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'filterMenuByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getAllActiveOrders' : IDL.Func([], [IDL.Vec(LiveOrder)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FoodCourtProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartItems' : IDL.Func([], [Cart], ['query']),
  'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [MenuItem], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getSingleRestaurant' : IDL.Func([], [Restaurant], ['query']),
  'getStandardizedRestaurantContactInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FoodCourtProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([FoodCourtProfile], [], []),
  'searchMenuByName' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'updateCartItems' : IDL.Func(
      [IDL.Vec(UpdateCartItemInput), IDL.Bool],
      [Cart],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'uuid' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantUuid' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'menuItemUuid' : IDL.Text,
    'restaurantUuid' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const OrderMenuItem = IDL.Record({
    'uuid' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const LiveOrder = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'customerPhone' : IDL.Text,
    'orderId' : IDL.Text,
    'items' : IDL.Vec(OrderMenuItem),
    'totalPrice' : IDL.Nat,
    'orderTimestamp' : IDL.Int,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'customerPhone' : IDL.Text,
    'userId' : IDL.Principal,
    'userNotes' : IDL.Text,
    'uuid' : IDL.Text,
    'restaurantId' : IDL.Text,
    'items' : IDL.Vec(OrderMenuItem),
    'totalPrice' : IDL.Nat,
    'orderTimestamp' : IDL.Int,
  });
  const FoodCourtProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Cart = IDL.Vec(CartItem);
  const CuisineType = IDL.Variant({
    'other' : IDL.Text,
    'chicken' : IDL.Null,
    'chinese' : IDL.Null,
    'healthy' : IDL.Null,
    'mexican' : IDL.Null,
    'fastFood' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'american' : IDL.Null,
    'pizza' : IDL.Null,
    'burger' : IDL.Null,
    'barbecue' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'name' : IDL.Text,
    'uuid' : IDL.Text,
    'cuisineType' : CuisineType,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const UpdateCartItemInput = IDL.Record({
    'menuItemUuid' : IDL.Text,
    'quantity' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'addSearchHistory' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearActiveOrders' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'filterMenuByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getAllActiveOrders' : IDL.Func([], [IDL.Vec(LiveOrder)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(FoodCourtProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartItems' : IDL.Func([], [Cart], ['query']),
    'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [MenuItem], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getSingleRestaurant' : IDL.Func([], [Restaurant], ['query']),
    'getStandardizedRestaurantContactInfo' : IDL.Func(
        [],
        [IDL.Text],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FoodCourtProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([FoodCourtProfile], [], []),
    'searchMenuByName' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'updateCartItems' : IDL.Func(
        [IDL.Vec(UpdateCartItemInput), IDL.Bool],
        [Cart],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };