/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrderMenuItem {
    uuid: string;
    quantity: bigint;
    price: bigint;
}
export interface LiveOrder {
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    orderId: string;
    currentLongitude?: number;
    lastLocationUpdate?: bigint;
    items: Array<OrderMenuItem>;
    totalPrice: bigint;
    currentLatitude?: number;
    orderTimestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UpdateCartItemInput {
    menuItemUuid: string;
    quantity?: bigint;
}
export type CuisineType = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "chicken";
    chicken: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "healthy";
    healthy: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "fastFood";
    fastFood: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
} | {
    __kind__: "pizza";
    pizza: null;
} | {
    __kind__: "burger";
    burger: null;
} | {
    __kind__: "barbecue";
    barbecue: null;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Restaurant {
    name: string;
    uuid: string;
    cuisineType: CuisineType;
    description: string;
    website: string;
    address: string;
    phone: string;
    profilePicture?: ExternalBlob;
}
export interface Order {
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    userId: Principal;
    userNotes: string;
    uuid: string;
    restaurantId: string;
    items: Array<OrderMenuItem>;
    totalPrice: bigint;
    orderTimestamp: bigint;
}
export interface MenuItem {
    name: string;
    uuid: string;
    isAvailable: boolean;
    description: string;
    restaurantUuid: string;
    category: string;
    image?: ExternalBlob;
    price: bigint;
}
export interface UpdateOrderLocationInput {
    latitude: number;
    orderId: string;
    longitude: number;
}
export interface FoodCourtProfile {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface CartItem {
    menuItemUuid: string;
    restaurantUuid: string;
    quantity: bigint;
    price: bigint;
}
export type Cart = Array<CartItem>;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    rejected = "rejected",
    delivered = "delivered",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptOrder(orderId: string): Promise<void>;
    addMenuItem(menuItem: MenuItem): Promise<void>;
    addSearchHistory(search: string): Promise<void>;
    addToCart(item: CartItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearActiveOrders(): Promise<void>;
    clearCart(): Promise<void>;
    deleteMenuItem(uuid: string): Promise<void>;
    filterMenuByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<MenuItem>>;
    getAllActiveOrders(): Promise<Array<LiveOrder>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrders(): Promise<Array<Order>>;
    getCallerUserProfile(): Promise<FoodCourtProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCartItems(): Promise<Cart>;
    getLiveOrderLocation(orderId: string): Promise<{
        latitude: number;
        longitude: number;
        lastLocationUpdate: bigint;
    } | null>;
    getMenuByCategory(category: string): Promise<Array<MenuItem>>;
    getMenuItem(uuid: string): Promise<MenuItem>;
    getOrder(uuid: string): Promise<Order>;
    getSingleRestaurant(): Promise<Restaurant>;
    getStandardizedRestaurantContactInfo(): Promise<string>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<FoodCourtProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markOrderAsDelivered(uuid: string): Promise<void>;
    placeOrder(address: string, userNotes: string, customerName: string, customerPhone: string): Promise<string>;
    rejectOrder(orderId: string): Promise<void>;
    removeFromCart(menuItemUuid: string): Promise<void>;
    saveCallerUserProfile(profile: FoodCourtProfile): Promise<void>;
    searchMenuByName(searchTerm: string): Promise<Array<MenuItem>>;
    updateCartItems(items: Array<UpdateCartItemInput>, keepItemsWithQuantityZero: boolean): Promise<Cart>;
    updateCustomerLocationOnOrder(input: UpdateOrderLocationInput): Promise<void>;
    updateMenuItem(uuid: string, newName: string | null, newDescription: string | null, newPrice: bigint | null, newCategory: string | null, newIsAvailable: boolean | null, newImage: ExternalBlob | null): Promise<void>;
    updateOrderStatus(uuid: string, status: OrderStatus): Promise<void>;
}
import type { CuisineType as _CuisineType, ExternalBlob as _ExternalBlob, FoodCourtProfile as _FoodCourtProfile, LiveOrder as _LiveOrder, MenuItem as _MenuItem, Order as _Order, OrderMenuItem as _OrderMenuItem, OrderStatus as _OrderStatus, Restaurant as _Restaurant, UpdateCartItemInput as _UpdateCartItemInput, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrder(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(await to_candid_MenuItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(await to_candid_MenuItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSearchHistory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSearchHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSearchHistory(arg0);
            return result;
        }
    }
    async addToCart(arg0: CartItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearActiveOrders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearActiveOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearActiveOrders();
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async deleteMenuItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async filterMenuByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterMenuByPriceRange(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterMenuByPriceRange(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveOrders(): Promise<Array<LiveOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveOrders();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveOrders();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<FoodCourtProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCartItems(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCartItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCartItems();
            return result;
        }
    }
    async getLiveOrderLocation(arg0: string): Promise<{
        latitude: number;
        longitude: number;
        lastLocationUpdate: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveOrderLocation(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveOrderLocation(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuByCategory(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuByCategory(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItem(arg0: string): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_MenuItem_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_MenuItem_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSingleRestaurant(): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.getSingleRestaurant();
                return from_candid_Restaurant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSingleRestaurant();
            return from_candid_Restaurant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStandardizedRestaurantContactInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandardizedRestaurantContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandardizedRestaurantContactInfo();
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<FoodCourtProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markOrderAsDelivered(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderAsDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderAsDelivered(arg0);
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrder(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: FoodCourtProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchMenuByName(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMenuByName(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMenuByName(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItems(arg0: Array<UpdateCartItemInput>, arg1: boolean): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItems(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItems(to_candid_vec_n36(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateCustomerLocationOnOrder(arg0: UpdateOrderLocationInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerLocationOnOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerLocationOnOrder(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: string, arg1: string | null, arg2: string | null, arg3: bigint | null, arg4: string | null, arg5: boolean | null, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n42(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n42(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CuisineType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuisineType): CuisineType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LiveOrder_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveOrder): LiveOrder {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_MenuItem_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): Promise<MenuItem> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Restaurant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Promise<Restaurant> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodCourtProfile]): FoodCourtProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        latitude: number;
        longitude: number;
        lastLocationUpdate: bigint;
    }]): {
    latitude: number;
    longitude: number;
    lastLocationUpdate: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    uuid: string;
    isAvailable: boolean;
    description: string;
    restaurantUuid: string;
    category: string;
    image: [] | [_ExternalBlob];
    price: bigint;
}): Promise<{
    name: string;
    uuid: string;
    isAvailable: boolean;
    description: string;
    restaurantUuid: string;
    category: string;
    image?: ExternalBlob;
    price: bigint;
}> {
    return {
        name: value.name,
        uuid: value.uuid,
        isAvailable: value.isAvailable,
        description: value.description,
        restaurantUuid: value.restaurantUuid,
        category: value.category,
        image: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    orderId: string;
    currentLongitude: [] | [number];
    lastLocationUpdate: [] | [bigint];
    items: Array<_OrderMenuItem>;
    totalPrice: bigint;
    currentLatitude: [] | [number];
    orderTimestamp: bigint;
}): {
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    orderId: string;
    currentLongitude?: number;
    lastLocationUpdate?: bigint;
    items: Array<OrderMenuItem>;
    totalPrice: bigint;
    currentLatitude?: number;
    orderTimestamp: bigint;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n21(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        customerPhone: value.customerPhone,
        orderId: value.orderId,
        currentLongitude: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.currentLongitude)),
        lastLocationUpdate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastLocationUpdate)),
        items: value.items,
        totalPrice: value.totalPrice,
        currentLatitude: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.currentLatitude)),
        orderTimestamp: value.orderTimestamp
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    userId: Principal;
    userNotes: string;
    uuid: string;
    restaurantId: string;
    items: Array<_OrderMenuItem>;
    totalPrice: bigint;
    orderTimestamp: bigint;
}): {
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    customerPhone: string;
    userId: Principal;
    userNotes: string;
    uuid: string;
    restaurantId: string;
    items: Array<OrderMenuItem>;
    totalPrice: bigint;
    orderTimestamp: bigint;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n21(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        customerPhone: value.customerPhone,
        userId: value.userId,
        userNotes: value.userNotes,
        uuid: value.uuid,
        restaurantId: value.restaurantId,
        items: value.items,
        totalPrice: value.totalPrice,
        orderTimestamp: value.orderTimestamp
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    uuid: string;
    cuisineType: _CuisineType;
    description: string;
    website: string;
    address: string;
    phone: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    uuid: string;
    cuisineType: CuisineType;
    description: string;
    website: string;
    address: string;
    phone: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        name: value.name,
        uuid: value.uuid,
        cuisineType: from_candid_CuisineType_n34(_uploadFile, _downloadFile, value.cuisineType),
        description: value.description,
        website: value.website,
        address: value.address,
        phone: value.phone,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    rejected: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "rejected" in value ? OrderStatus.rejected : "delivered" in value ? OrderStatus.delivered : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    chicken: null;
} | {
    chinese: null;
} | {
    healthy: null;
} | {
    mexican: null;
} | {
    fastFood: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    american: null;
} | {
    pizza: null;
} | {
    burger: null;
} | {
    barbecue: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "chicken";
    chicken: null;
} | {
    __kind__: "chinese";
    chinese: null;
} | {
    __kind__: "healthy";
    healthy: null;
} | {
    __kind__: "mexican";
    mexican: null;
} | {
    __kind__: "fastFood";
    fastFood: null;
} | {
    __kind__: "italian";
    italian: null;
} | {
    __kind__: "indian";
    indian: null;
} | {
    __kind__: "american";
    american: null;
} | {
    __kind__: "pizza";
    pizza: null;
} | {
    __kind__: "burger";
    burger: null;
} | {
    __kind__: "barbecue";
    barbecue: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "chicken" in value ? {
        __kind__: "chicken",
        chicken: value.chicken
    } : "chinese" in value ? {
        __kind__: "chinese",
        chinese: value.chinese
    } : "healthy" in value ? {
        __kind__: "healthy",
        healthy: value.healthy
    } : "mexican" in value ? {
        __kind__: "mexican",
        mexican: value.mexican
    } : "fastFood" in value ? {
        __kind__: "fastFood",
        fastFood: value.fastFood
    } : "italian" in value ? {
        __kind__: "italian",
        italian: value.italian
    } : "indian" in value ? {
        __kind__: "indian",
        indian: value.indian
    } : "american" in value ? {
        __kind__: "american",
        american: value.american
    } : "pizza" in value ? {
        __kind__: "pizza",
        pizza: value.pizza
    } : "burger" in value ? {
        __kind__: "burger",
        burger: value.burger
    } : "barbecue" in value ? {
        __kind__: "barbecue",
        barbecue: value.barbecue
    } : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Promise<Array<MenuItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MenuItem_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveOrder>): Array<LiveOrder> {
    return value.map((x)=>from_candid_LiveOrder_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n26(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MenuItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): Promise<_MenuItem> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCartItemInput_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCartItemInput): _UpdateCartItemInput {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    menuItemUuid: string;
    quantity?: bigint;
}): {
    menuItemUuid: string;
    quantity: [] | [bigint];
} {
    return {
        menuItemUuid: value.menuItemUuid,
        quantity: value.quantity ? candid_some(value.quantity) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    uuid: string;
    isAvailable: boolean;
    description: string;
    restaurantUuid: string;
    category: string;
    image?: ExternalBlob;
    price: bigint;
}): Promise<{
    name: string;
    uuid: string;
    isAvailable: boolean;
    description: string;
    restaurantUuid: string;
    category: string;
    image: [] | [_ExternalBlob];
    price: bigint;
}> {
    return {
        name: value.name,
        uuid: value.uuid,
        isAvailable: value.isAvailable,
        description: value.description,
        restaurantUuid: value.restaurantUuid,
        category: value.category,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none(),
        price: value.price
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    rejected: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.rejected ? {
        rejected: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<UpdateCartItemInput>): Array<_UpdateCartItemInput> {
    return value.map((x)=>to_candid_UpdateCartItemInput_n37(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
